### ISSUE TITLE
sudo issue on script

### ISSUE THREAD

**Issue by Lucif3r-MorningSter** [liaralabs/swizzin#239]
diskspace and panel disk widget is hitting cpu usage with sudo command on scripts

"journalctl --no-full -f" result:
www-data : TTY=unknown ; PWD=/srv/panel/widgets ; USER=root ; COMMAND=/usr/sbin/repquota /
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root

 log is being filled by these and cpu usage is high on htop /sbin/init

 - OS: Debian 10

**Comment by liaralabs** [comment]
The sudo log is normal stuff. `repquota` needs to be called with `sudo` or the command will fail. Every time sudo is called, an entry is created in journalctl with the details of that call.

I'm changing `repquota` out for `quota` which is easier on resources if you have several disks on your server (read: the command returns its output considerably faster than `repquota`). Beyond that there's not much I can do to increase performance with the panel code the way it is. If you want to use the panel, you need to be aware of the potential performance implications. This is why swizzin is modular -- you can choose the packages that work best for you. As far as the panel is concerned, I'm not a PHP dev, so you would be misplacing your trust to expect any major rehauls to **QuickBox's ported panel code**.

However, beyond some resource usage, unless you have a lot of users on your server I don't see this command spiking CPU usage on your server. The disk quota refresh is only called every 15 seconds, which, unless your server CPU is a potato, should not be overly taxing of your CPU calls. I'd be willing to bet your /sbin/init cpu usage is coming from somewhere else.

If you're running a server with **a lot** of users, please bear in mind that this version of swizzin was never intended to be supporting super busy environment with a lot of users -- thus many aspects of a multi-user environment are not optimized.

**Comment by Lucif3r-MorningSter** [comment]
disks[ace on rutorrent gone blank after update

**Comment by liaralabs** [comment]
Apologies -- should be fixed now.

**Comment by Lucif3r-MorningSter** [comment]
well this doesn't fix it at all. however disabling journal is a temporary fix for this .

**Comment by Lucif3r-MorningSter** [comment]
sent you a mail 2days ago. if you have time pls ans.
