### ISSUE TITLE
Jackett - admin password

### ISSUE THREAD

**Issue by Bishop-trevorstuart** [liaralabs/swizzin#413]
## Bug description
Fresh install or a re-install of Jackett is not allowing access via webUI. 
trying the password for the account that was setup as master in Box setup

## Reproduction steps
1. Install package 'jackett'
2. Go to 'webui'
3. Error 'No error, just won't log in'

## Installed applications through swizzin
(Nginx, panel, deluge, jackett, radarr, sonarr, ombi)

## Expected behavior
Should allow log in to WebUI using the master password

## Server Info
**(please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Image Source: ubuntu-20.04.1-live-server-amd64.iso

## Is Swizzin up to date?
HEAD is now at bc6b189

## Additional context
Other applications appear to work with master password. Deluge is likely best example. I CAN get into the WebUI for it using the master password. Just Jackett appears to not be working.

(Good sources for log output could be the following: (only if they have relevant information))
Sorry I'm not sure which will have info that helps (I'm very new to this, but learning)
- `cat /root/logs/install.log` - https://termbin.com/8d5e2
- `cat /root/logs/swizzin.log` - https://termbin.com/5uzr
- `systemctl status jackett@tstuart.service` - https://termbin.com/ts62x
- `journalctl -xe` - https://termbin.com/g26p

**Comment by liaralabs** [comment]
Does your password contain any odd characters?

The password is set directly with the jackett api via a curl command:

```
cookie=$(curl -v 127.0.0.1:9117/jackett/UI/Dashboard -L 2>&1 | grep -m1 Set-Cookie | awk '{printf $3}' | sed 's/;//g')
curl http://127.0.0.1:9117/jackett/api/v2.0/server/adminpassword -H 'Content-Type: application/json' -H 'Cookie: '${cookie}'' --data-binary '"'${password}'"'
```

The fact that you have a password is proof the function worked (you would not have an login page otherwise), my guess is a special character interfered with the command and truncated it, leaving you with a different password.

**Comment by Bishop-trevorstuart** [comment]
This is not the actual password but an example, same number of charters/1 capital to start/1 number at the end...
Swizzins7

I tried adding a : to the beginning, thinking maybe it pulled extra charters from the master file. But I"m shooting blind if it did truncate.
I can try running the same command manually and have it out put result to shell then at least I'd know. Tried just the curl but it didn't post anything forme to see.

**Comment by liaralabs** [comment]
It actually looks like upon removal that the Jackett config wasn't being removed so your password likely never was reset from the first installation. This should be fixed if you update and then uninstall jackett (or just `rm -r /home/username/.config/Jackett`)

The password itself looks like it should be being set without issue as it's alphanumeric.

**Comment by Bishop-trevorstuart** [comment]
Unfortunetly still not working. 
updated box
uninstalled jackett, then reinstalled jackett - same issue.
Then tried just sudo rm -r /home/username/.config/Jackett and reloading the webUI. Same problem.

**Comment by Bishop-trevorstuart** [comment]
Just tried with Edge, normally use chrome, so this would eliminate any cookies potentially. 
When openedin Edge I got promoted for both username and password, did not get this from chrome. 
Used my master usernmae/password. 
I then got the webUI - put in the password and it's working. 
Is this something I'm doing wrong

**Comment by liaralabs** [comment]
You may have cache stored for this domain somewhere if this is the case as I was going to say that I'm not able to reproduce the issue at all, even using your demo password.

You may just need to clear the cache/domain settings for your domain or IP.

**Comment by Bishop-trevorstuart** [comment]
That appears to be the issue. Sorry about the flase bug report.
