### ISSUE TITLE
Wireguard PPA discontinued

### ISSUE THREAD

**Issue by Wyall** [liaralabs/swizzin#420]
## Bug description
The Wireguard PPA (at least for Ubuntu 18.04) got discontinued as it seems. 
apt update reports:
```
Err:11 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
```
and apt upgrade:
```
E: The repository 'http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

## Reproduction steps
Do apt upgrade with Wireguard installed

## Server Info
 - OS: Ubuntu 18.04

## Is Swizzin up to date?
e5b3f0f

**Comment by flying-sausages** [comment]
Issue #420 

![image](https://user-images.githubusercontent.com/23618693/95580254-55915900-0a37-11eb-86e5-88cdcdef80a3.png)

Looks like it got moved indeed https://github.com/EggieCode/wireguard-ppa

**Comment by liaralabs** [comment]
So wireguard has been mainlined in a 4 year old stable LTS distro. Can't understand the reasoning behind this massive backport making breaking changes to implemented solutions. It's not exactly stable thinking for Ubuntu to push a change like this to Xenial and Bionic.

Since I don't main Ubuntu, I'm looking for suggestions on how to handle this. `ppa-purge` would be the easiest way to handle this (it downgrades packages itself automatically); however, it's an extra depend which is not installed as of yet. We can do our own `ppa-purge` but it'll be a bit more complicated but similar to the backports change I just implemented for Buster:

```
codename=$(lsb_release -cs)
if [[ $codname =~ ("xenial"|"buster") ]]; then
    add-apt-repository --remove ppa:wireguard/wireguard
    apt-get -y --allow-downgrades install wireguard/${codename}-updates wireguard-tools/${codename}-updates wireguard-dkms/${codename}-updates
fi
```

That said it looks like we may also need a function to ensure the `updates` repository is turned on for Ubuntu as it's not in the regular repos

Since the PPA itself has been removed, this is not actually something I can setup a test for myself :sweat_smile:

**Comment by liaralabs** [comment]
Ok, I've just pushed an update that should cover this on new and existing installs.

If you `box update` at this point, if detected, the wireguard PPA will be removed along with the ppa packages. Wireguard will then be reinstalled using the updates repo, at which point wireguard-dkms should no longer be required since Ubuntu's mainline kernels are now shipping with the wireguard module built-in.

**Comment by Wyall** [comment]
Okay as you don't have Ubuntu I will just post my output. 

https://0bin.net/paste/+BNAsoRx#kQr7Sp6z3wJCcO0BwRWZckK36QmbkSdynXmLiUOxXaW

Afterwards I still get
Err:9 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]

**Comment by liaralabs** [comment]
That's very strange, the log thinks I asked it to add the repo despite `--remove` being in the command and I tested this on a bionic server as well. Let me investigate.

**Comment by liaralabs** [comment]
@Wyall can you please test the new commit? The sources are being manually removed now since it looks like we can't use the `apt-add-repository` command if the PPA doesn't exist anymore.

**Comment by Wyall** [comment]
This seems to work now, thank you very much! I thought it might be my system again, sometimes it has hickup
https://0bin.net/paste/8vxtOLCk#8IiRkxXBukQliwFc2sKhej+verW4Fvn4XoEPSStTPEj

**Comment by liaralabs** [comment]
Great! Closing as this is now resolved.
